# This is a basic workflow to help you get started with Actions

name: Update Migrations

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync-migrations-branch:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Merge master -> migrations
        run: uses devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: migrations
          github_token: ${{ github.token }}
